# Generated by Django 5.2.4 on 2026-01-24 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='settled_by',
            field=models.ManyToManyField(blank=True, related_name='settled_splits', to=settings.AUTH_USER_MODEL),
        ),
    ]
