# Generated by Django 5.2.4 on 2025-07-27 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Group Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Group Description (optional)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="group_images/",
                        verbose_name="Group Image",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Set an optional budget for this group (e.g., 5000.00)",
                        max_digits=10,
                        null=True,
                        verbose_name="Group Budget (Optional)",
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("Trip", "Trip"),
                            ("Home", "Home"),
                            ("Others", "Others"),
                        ],
                        default="Others",
                        max_length=10,
                        verbose_name="Group Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Start Date (for Trips)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="End Date (for Trips)"
                    ),
                ),
                (
                    "individual_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: Budget per person for this trip",
                        max_digits=10,
                        null=True,
                        verbose_name="Individual Budget (for Trips)",
                    ),
                ),
                (
                    "monthly_home_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: Monthly budget for this home group",
                        max_digits=10,
                        null=True,
                        verbose_name="Monthly Home Budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Group Members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invited_email",
                    models.EmailField(max_length=254, verbose_name="Invited Email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("decline", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="groups.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "ordering": ["-created_at"],
                "unique_together": {("group", "invited_email", "status")},
            },
        ),
    ]
