# Generated by Django 5.2.4 on 2026-01-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
